### ISSUE TITLE
Подготовить аудио файл для анализа

### ISSUE THREAD

**Issue by nikitavasilev03** [nikitavasilev03/NIR#5]
1. Установить программу Audacity
2. Записать звуковой файл в программе 
3. Требования к файлу: WAV (Microsoft) с подписью 16-бит PCM
4. Экспортировать файл с указанными требованиями
5. Перенести файл в папку с проектом bin\Debug\

**Comment by stepanarakel** [comment]
1. Установлена программа Audacity
2. Записан звуковой файл Test1.wav
3. Файл отвечает требованиям WAV (Microsoft) с подписью 16-бит PCM
4. Файл экспортирован
5. Файл перенесён в папку с проектом bin\Debug\
