### ISSUE TITLE
Создание решения в Visual Studio 2017

### ISSUE THREAD

**Issue by nikitavasilev03** [nikitavasilev03/NIR#6]
1. Создать новое решение в Visual Studio 2017
2. Добавить созданное решение в Git репозиторий
3. Создание удаленного репозитория на GitHub и добавление в него решение
4. Добавление Соавторов
5. Создание проекта в решении NIR (итоговый Windows Form проект)
6. Создание проекта в решении Audio (тестовый ConsoleApplication проект для облегчения тестирования и отладки реализованных задач)

**Comment by statzky** [comment]
1. Было создано решение Visual Studio 2017
2. Созданное решение было добавлено в репозиторий Git 
3. С помощью GitHub был создан удалённый репозиторий (из под аккаунта nikitavasilev03) в который было добавлено решение из пункта 1.
4. Были добавлены соавторы проекта (stepanarakel и statzky)
5. Был создан проект в решении NIR (итоговый проект Windows Forms)
6. Был создан проект в решении Audio (тестовый ConsoleApllication проект для облегчения тестирования и отладки реализованных на данный момент задач)
